// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KanyonVSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "KanyonVSIX.24da5627-bfea-4864-8e19-83def4a1e01c";
        public const string Name = "KanyonVSIX";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Eric Montgomery";
        public const string Tags = "";
    }
}
