// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KanyonVSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string KanyonVSIXString = "f6db77c1-31d0-456a-b7e5-70600fd0524b";
        public static Guid KanyonVSIX = new Guid(KanyonVSIXString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
        public const int ToolbarID = 0x1000;
        public const int ToolbarGroupID = 0x1001;
        public const int cmdProjectComboSelect = 0x1011;
        public const int cmdProjectComboPopulate = 0x1012;
    }
}